### ISSUE TITLE
Encoding error when attempting to write executed notebook to html

### ISSUE THREAD

**Issue by yil532** [elyra-ai/kfp-notebook#15]
Issue occurs while running DAX notebook, talked to Alan through Slack @akchinSTC 
Here is the error message:
```
Imports Complete.....
Parsing Arguments.....
Get file Part 3 - Time Series Forecasting-81cf9a55-9648-4245-8d16-6d35ee8f50da.tar.gz from bucket yil532
TAR Archive pulled from Object Storage.
Unpacking........
Unpacking Complete.
Executing notebook through Papermill: Part 3 - Time Series Forecasting.ipynb ==> Part 3 - Time Series Forecasting_output.ipynb
Converting from ipynb to html....
Traceback (most recent call last):
  File "bootstrapper.py", line 148, in <module>
    output_html_file = notebook_to_html(input_params['output'], input_params['output-html'])
  File "bootstrapper.py", line 58, in notebook_to_html
    f.write(data)
UnicodeEncodeError: 'ascii' codec can't encode character '\xa9' in position 573616: ordinal not in range(128)
```

**Comment by yil532** [comment]
Issue solved in slack.
