### ISSUE TITLE
bootstrapper always tries to establish unsecure COS connection

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/kfp-notebook#94]
In https://github.com/elyra-ai/kfp-notebook/blob/master/etc/docker-scripts/bootstrapper.py#L75-L78 the client is always configured to utilize an unsecured (`http`) connection even though the S3 endpoint might be secured (e.g. `https://s3-openshift-storage.apps.zero.massopen.cloud/`).

The following information is displayed in the pod log file:

```
...
[I 23:16:17.874] 'untitled-0422231504':'Untitled' - Packages installed (27.886 secs)
[I 23:16:17.985] 'untitled-0422231504':'Untitled' - processing dependencies 
[D 23:16:17.986] Starting new HTTP connection (1): s3-openshift-storage.apps.zero.massopen.cloud:80
[D 23:16:17.993] 
http://s3-openshift-storage.apps.zero.massopen.cloud:80
 "GET /opf-datacatalog?location= HTTP/1.1" 503 None
[D 23:16:17.994] Incremented Retry for (url='/opf-datacatalog?location='): Retry(total=4, connect=None, read=None, redirect=None, status=None)
[D 23:16:17.994] Retry: /opf-datacatalog?location=
[D 23:16:17.994] Resetting dropped connection: s3-openshift-storage.apps.zero.massopen.cloud
[D 23:16:17.996] 
http://s3-openshift-storage.apps.zero.massopen.cloud:80
 "GET /opf-datacatalog?location= HTTP/1.1" 503 None
[D 23:16:17.997] Incremented Retry for (url='/opf-datacatalog?location='): Retry(total=3, connect=None, read=None, redirect=None, status=None)
[D 23:16:18.397] Retry: /opf-datacatalog?location=
[D 23:16:18.398] Resetting dropped connection: s3-openshift-storage.apps.zero.massopen.cloud
[D 23:16:18.401] 
http://s3-openshift-storage.apps.zero.massopen.cloud:80
 "GET /opf-datacatalog?location= HTTP/1.1" 503 None
[D 23:16:18.401] Incremented Retry for (url='/opf-datacatalog?location='): Retry(total=2, connect=None, read=None, redirect=None, status=None)
[D 23:16:19.202] Retry: /opf-datacatalog?location=
[D 23:16:19.202] Resetting dropped connection: s3-openshift-storage.apps.zero.massopen.cloud
[D 23:16:19.205] 
http://s3-openshift-storage.apps.zero.massopen.cloud:80
 "GET /opf-datacatalog?location= HTTP/1.1" 503 None
[D 23:16:19.206] Incremented Retry for (url='/opf-datacatalog?location='): Retry(total=1, connect=None, read=None, redirect=None, status=None)
[D 23:16:20.807] Retry: /opf-datacatalog?location=
[D 23:16:20.807] Resetting dropped connection: s3-openshift-storage.apps.zero.massopen.cloud
[D 23:16:20.810] 
http://s3-openshift-storage.apps.zero.massopen.cloud:80
 "GET /opf-datacatalog?location= HTTP/1.1" 503 None
[D 23:16:20.811] Incremented Retry for (url='/opf-datacatalog?location='): Retry(total=0, connect=None, read=None, redirect=None, status=None)
[D 23:16:24.014] Retry: /opf-datacatalog?location=
[D 23:16:24.015] Resetting dropped connection: s3-openshift-storage.apps.zero.massopen.cloud
[D 23:16:24.018] 
http://s3-openshift-storage.apps.zero.massopen.cloud:80
 "GET /opf-datacatalog?location= HTTP/1.1" 503 None
Traceback (most recent call last):
  File "bootstrapper.py", line 626, in <module>
    main()
  File "bootstrapper.py", line 614, in main
    file_op.process_dependencies()
  File "bootstrapper.py", line 98, in process_dependencies
    self.get_file_from_object_storage(archive_file)
  File "bootstrapper.py", line 283, in get_file_from_object_storage
    self.cos_client.fget_object(bucket_name=self.cos_bucket,
  File "/opt/app-root/src/jupyter-work-dir/python3/minio/api.py", line 719, in fget_object
    stat = self.stat_object(bucket_name, object_name, sse)
  File "/opt/app-root/src/jupyter-work-dir/python3/minio/api.py", line 1138, in stat_object
    response = self._url_open('HEAD', bucket_name=bucket_name,
  File "/opt/app-root/src/jupyter-work-dir/python3/minio/api.py", line 1984, in _url_open
    region = self._get_bucket_region(bucket_name)
  File "/opt/app-root/src/jupyter-work-dir/python3/minio/api.py", line 1919, in _get_bucket_region
    region = self._get_bucket_location(bucket_name)
  File "/opt/app-root/src/jupyter-work-dir/python3/minio/api.py", line 1948, in _get_bucket_location
    response = self._http.urlopen(method, url,
  File "/opt/app-root/src/jupyter-work-dir/python3/urllib3/poolmanager.py", line 336, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/opt/app-root/src/jupyter-work-dir/python3/urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "/opt/app-root/src/jupyter-work-dir/python3/urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "/opt/app-root/src/jupyter-work-dir/python3/urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
  [Previous line repeated 2 more times]
  File "/opt/app-root/src/jupyter-work-dir/python3/urllib3/connectionpool.py", line 805, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/opt/app-root/src/jupyter-work-dir/python3/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='s3-openshift-storage.apps.zero.massopen.cloud', port=80): Max retries exceeded with url: /opf-datacatalog?location= (Caused by ResponseError('too many 503 error responses'))

```

**Comment by ptitzler** [comment]
See https://github.com/elyra-ai/elyra/blob/master/elyra/util/cos.py#L39 how this was handled i the pipeline editor.
